### ISSUE TITLE
Do you know AdminLTE Control Panel Template

### ISSUE THREAD

**Issue by witwall** [goFrendiAsgard/No-CMS#153]
[AdminLTE](https://github.com/almasaeed2010/AdminLTE) -- is a fully responsive admin template. Based on Bootstrap 3 framework. Highly customisable and easy to use. Fits many screen resolutions from small mobile devices to large desktops.

No-CMS is great, if No-CMS can integrate with AdminLTE, it would be greater!

**Comment by noogen** [comment]
Agree!  I like No-CMS because, well, it's not a CMS?   There are many choices for CMS out there and I've been looking for Admin Control Panel CMS like capability.  No-CMS seem to be exactly what I'm looking for.  It provide excellent out of the box User Management System.  You can easily manage group and permissions.  This is what set it apart from the rest.  

Future Enhancements Suggestion
======================

Why try to compete with other CMS for things like blog?   I think there should be more focus on Admin Panel and Security.   Maybe even have a module/app like marketplace to make $$$ with.   Everyone, including goFrendi, can develop plugins and make $ from this marketplace.  The author can also setup to make 10-30% on top of the Sale.  I, and many other developer, would not mind this at all.  This is what everyone does, including Apple.  This will help keep the platform alive.  I would like to see this platform grow.

I will try to implement AdminLTE theme myself.  I don't really know much about the stuff use in this framework, including codeigniter.  But everything seem to be looking simple enough.  Hopefully, some of my Slim and Laravel knowledge may help.

**Comment by noogen** [comment]
Wow, I'm seriously rethinking this.  It doesn't look like it'll be easy to theme.   Very hard coded to bootstrap default layout.  Layout code and nav widget are everywhere.  Sorry, I'm giving up already.

**Comment by witwall** [comment]
never mind.
